# Supported funding model platforms
github: [ANAMIZED]
custom:
  - "https://buy.stripe.com/bJe3cw0kCaLrbVz1AY43S09"
  - "https://buy.stripe.com/9B68wQ1oGcTz9NrfrO43S0a"
  - "https://donate.stripe.com/00w5kE3wOg5L8Jn2F243S00"
